management:
  health:
    diskspace:
      enabled: "true"
    default:
      enabled: "true"
    db:
      enabled: "true"
  servlet:
    context-path: /manage
spa:
  default-file: /dist/index.html5
spring:
  web:
    resources:
      static-locations: classpath:/dist/
      add-mappings: "false"
  jpa:
    properties:
      hibernate:
        format_sql: 'true'
        show_sql: 'true'
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    # SQL스크립트는 Hibernate가 초기화되기 전에 실행되는데, 스크립트를 사용하여 hibernate에 의해
    # 생성된 테이블에 데이터를 채우려면 아래의 설정을 true로 해야 한다.
    defer-datasource-initialization: true
  database-platform: org.hibernate.dialect.H2Dialect
  # data.sql 실행을 위한 추가
  sql:
    init:
      mode: always
  datasource:
    driverClassName: org.h2.Driver
    password: ''
    username: sa
    hikari:
      jdbc-url: jdbc:h2:tcp://localhost/~/richMinime;NON_KEYWORDS=USER
#    url: jdbc:h2:mem:testdb;NON_KEYWORDS=USER
  h2:
    console:
      path: /h2-console
      enabled: true
  profiles:
    include: secure
  data:
    web:
      pageable:
        one-indexed-parameters: "true"
  mvc:
    throw-exception-if-no-handler-found: "true"
  devtools:
    livereload:
      enabled: "true"
  mail:
    host: smtp.gmail.com
    port: 587
    username:
    password:
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
  redis:
    host: localhost
    port: 6379
logging:
  level:
    org:
      org.hibernate.SQL: DEBUG
      org.hibernate.type.descriptor.sql.BasicBinder: TRACE
      org.springframework.boot: DEBUG
      org.springframework.security: DEBUG
      org.springframework.web: DEBUG
      apache:
        tiles: INFO
    root: INFO
    com:
      samsung:
        security: DEBUG
#  file:
#    name: ./ssafy-web.log 로그 저장
server:
  servlet:
    encoding:
      enabled: "true"
      force: "true"
      charset: UTF-8
    contextPath: /api
  address: localhost
  port: "8080"
  compression:
    enabled: "true"
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,application/javascript,text/css
build:
  date: "@build.date@"
jwt:
  expiration: '1296000000'
  cookieName: refresh-token
  secret: dyAeHubOOc8KaOfYB6XEQoEj1QzRlVgtjNL8PYs1A1tymZvvqkcEU7L1imkKHeDa
springfox:
  documentation:
    swagger:
      use-model-v3: 'false'

gpt:
  api-key: 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
